'use strict';
const $=id=>document.getElementById(id);let token=sessionStorage.getItem('klusfix_token'),user=null,selected='',analysis=null,caseId=null,image=null,register=false;
const categories=[['schilder','🎨','Schilderwerkzaamheden'],['stukadoor','🧱','Stukadoor'],['lekkage','💧','Lekkage / waterschade'],['verwarming','🔥','Verwarming'],['elektra','⚡','Elektra'],['sanitair','🚿','Sanitair'],['dak','🏠','Dak'],['muren','🧱','Muren / plafonds'],['vloer','🪵','Vloer'],['deuren','🚪','Deuren / ramen'],['schimmel','🦠','Schimmel / vocht'],['tuin','🌳','Tuin'],['ongedierte','🐜','Ongedierte'],['apparatuur','🔌','Apparatuur'],['overig','💡','Overige klus']];
const landingDetails={schilder:['Schilder','Binnen- en buitenschilderwerk'],stukadoor:['Stukadoor','Muren en plafonds stucen'],lekkage:['Loodgieter','Lekkage, sanitair en water'],verwarming:['Installateur','Verwarming en cv'],elektra:['Elektricien','Elektra en stroom'],sanitair:['Sanitair','Badkamer en toilet'],dak:['Dakdekker','Dak en dakbedekking'],muren:['Muren','Metselwerk en herstel'],vloer:['Vloer','Vloeren en afwerking'],deuren:['Deuren','Deuren en kozijnen'],schimmel:['Schimmel','Vochtbestrijding'],tuin:['Tuin','Tuinaanleg en onderhoud'],ongedierte:['Ongedierte','Ongediertebestrijding'],apparatuur:['Apparatuur','Reparatie en installatie'],overig:['Overige klus','Vertel ons wat je nodig hebt']};
// Vaste SVG-lijniconen: geen emoji of externe iconenbibliotheek nodig.
const iconPaths={
schilder:'<path d="M4 4h13v7H4z M17 7h3a2 2 0 0 1 2 2v2a2 2 0 0 1-2 2h-8v3 M12 18v4 M9 22h6"/><path class="paint-fill" d="M5 5h11v5H5z"/>',
stukadoor:'<path d="M3 14 19 5l2 4-16 9z M9 16l4 6 M7 18l4 4"/><path class="paint-fill" d="M4 14 19 6l1 2-15 9z"/>',
lekkage:'<path d="M12 2C9 7 5 11 5 15a7 7 0 0 0 14 0c0-4-4-8-7-13z M9 16a3 3 0 0 0 3 3"/>',
verwarming:'<path d="M10 14V5a2 2 0 0 1 4 0v9a5 5 0 1 1-4 0z M12 9v9"/>',
elektra:'<path d="m13 2-9 12h7l-1 8 10-13h-7z"/>',
sanitair:'<path d="M4 12h16v3a7 7 0 0 1-7 7h-2a7 7 0 0 1-7-7z M7 12V6a3 3 0 0 1 6 0 M11 6h4 M7 22v-2 M17 22v-2"/>',
dak:'<path d="m2 11 10-8 10 8 M5 10v11h14V10 M9 21v-7h6v7"/>',
muren:'<path d="M3 4h18v16H3z M3 9h18 M3 14h18 M3 19h18 M9 4v5 M16 9v5 M9 14v5"/>',
vloer:'<path d="M3 3h18v18H3z M12 3v18 M3 12h18 M3 3l9 9 M12 12l9 9"/>',
deuren:'<path d="M5 2h14v20H5z M8 5l8-1v16l-8-1z M13 12h1"/>',
schimmel:'<path d="M12 3v18 M4 12h16 M6 6l12 12 M18 6 6 18 M12 3l-2 3 M12 3l2 3 M3 12l3-2 M3 12l3 2"/>',
tuin:'<path d="M12 22V11 M12 15C4 15 3 9 4 5c6 0 8 4 8 10z M12 12c0-6 3-9 8-9 1 6-2 9-8 9z M7 22h10"/>',
ongedierte:'<path d="M8 8a4 4 0 0 1 8 0 M7 12a5 5 0 0 1 10 0v5a5 5 0 0 1-10 0z M12 12v10 M4 10l3 2 M20 10l-3 2 M3 16h4 M21 16h-4 M5 21l3-3 M19 21l-3-3"/>',
apparatuur:'<rect x="4" y="2" width="16" height="20" rx="2"/><circle cx="12" cy="14" r="5"/><path d="M7 6h2 M12 6h5"/>',
overig:'<path d="M12 2v4 M12 18v4 M2 12h4 M18 12h4 M5 5l3 3 M16 16l3 3 M19 5l-3 3 M8 16l-3 3"/>'};
function tradeIcon(id){return `<svg class="trade-svg trade-svg-${id}" viewBox="0 0 24 24" width="40" height="40" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${iconPaths[id]||iconPaths.overig}</svg>`}

let pendingGuest=false;
function renderLanding(){$('landingCategories').innerHTML=categories.filter(([id])=>id!=='overig').map(([id])=>{let [name,desc]=landingDetails[id];return `<button type="button" class="landing-card ${id==='schilder'||id==='stukadoor'?'featured':''}" data-landing="${id}"><span class="landing-icon">${tradeIcon(id)}</span><span class="landing-copy"><strong>${esc(name)}</strong><small>${esc(desc)}</small></span><span class="landing-arrow" aria-hidden="true">›</span></button>`}).join('')}
function openWork(id){selected=id;image=null;analysis=null;$('description').value='';$('postcode').value=user?.postcode||'';$('photo').value='';$('aiConsent').checked=false;$('preview').innerHTML='';renderCategories();show('report')}
$('landingCategories').onclick=e=>{let b=e.target.closest('[data-landing]');if(b)openWork(b.dataset.landing)};
$('otherWork').onclick=()=>openWork('overig');
$('brand').onclick=()=>show('landing');
$('accountBtn').onclick=()=>{if(user)show(user.role==='vakman'?'pro':'home');else show('auth')};
const trades=['Schilder','Stukadoor','Loodgieter','Elektricien','Installateur','Dakdekker','Vloerspecialist','Timmerman','Vochtbestrijder','Hovenier','Ongediertebestrijder','Reparateur','Allround klusbedrijf'];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
renderLanding();
function notice(t){$('notice').textContent=t;setTimeout(()=>{if($('notice').textContent===t)$('notice').textContent=''},6000)}
function show(id){document.querySelectorAll('.screen').forEach(s=>s.classList.toggle('active',s.id===id));scrollTo(0,0)}
async function api(route,method='GET',body){let r=await fetch('/api'+route,{method,headers:{'Content-Type':'application/json',...(token?{Authorization:'Bearer '+token}:{})},body:body?JSON.stringify(body):undefined});let data=await r.json();if(!r.ok){let e=new Error(data.error||'Er ging iets mis');e.data=data;throw e}return data}
function fail(e){notice(e.message||'Er ging iets mis')}
$('trade').innerHTML=trades.map(t=>`<option>${esc(t)}</option>`).join('');
$('role').onchange=()=>{$('tradeFields').hidden=$('role').value!=='vakman'};
$('authSwitch').onclick=()=>{register=!register;document.querySelectorAll('.registerOnly').forEach(el=>el.hidden=!register);$('authTitle').textContent=register?'Account aanmaken':'Inloggen';$('authSubmit').textContent=register?'Registreren':'Inloggen';$('authSwitch').textContent=register?'Ik heb al een account':'Nog geen account? Registreren';$('tradeFields').hidden=!register||$('role').value!=='vakman';$('password').autocomplete=register?'new-password':'current-password'};
$('authForm').onsubmit=async e=>{e.preventDefault();try{let data=await api(register?'/register':'/login','POST',{email:$('email').value,password:$('password').value,name:$('name').value,role:$('role').value,trade:$('trade').value,postcode:$('workPostcode').value});token=data.token;sessionStorage.setItem('klusfix_token',token);user=data.user;if(pendingGuest){pendingGuest=false;$('logout').hidden=false;$('accountBtn').textContent='Mijn overzicht';show('report')}else start()}catch(err){fail(err)}};
$('logout').onclick=async()=>{try{await api('/logout','POST',{})}catch{}sessionStorage.removeItem('klusfix_token');token=null;user=null;$('logout').hidden=true;$('accountBtn').textContent='Inloggen';show('landing')};
function start(){$('logout').hidden=false;$('accountBtn').textContent='Mijn overzicht';if(user.role==='vakman'){show('pro');$('proWelcome').textContent='Welkom, '+user.name;loadLeads()}else{$('welcome').textContent='Welkom, '+user.name;show('landing');loadCases()}}
async function loadCases(){try{let [c,r,q]=await Promise.all([api('/cases'),api('/requests'),api('/quotes')]);$('cases').innerHTML=c.cases.length?c.cases.map(x=>`<div class="case"><strong>${esc(categories.find(a=>a[0]===x.category)?.[2]||x.category)}</strong><small>${esc(x.created.slice(0,10))} · ${esc(x.analysis.trade)}</small><p>${esc(x.description)}</p><button data-match="${esc(x.id)}" data-trade="${esc(x.analysis.trade)}">Vind vakman →</button></div>`).join(''):'<div class="empty">Nog geen meldingen.</div>';$('myRequests').innerHTML=r.requests.length?r.requests.map(x=>`<div class="case"><b>${esc(x.tradeName)}</b><p>${esc(x.description)}</p><small>Status: ${esc(x.status)}</small></div>`).join(''):'<div class="empty">Nog geen aanvragen verstuurd.</div>';$('myQuotes').innerHTML=q.quotes.length?q.quotes.map(x=>`<div class="case"><b>${esc(x.tradeName)}</b><p>€ ${(x.amount_cents/100).toFixed(2)} — ${esc(x.details)}</p><small>Status: ${esc(x.status)}</small>${x.status==='aangeboden'?`<div><button data-quote="${esc(x.id)}" data-decision="geaccepteerd">Accepteren</button><button data-quote="${esc(x.id)}" data-decision="afgewezen">Afwijzen</button></div>`:''}</div>`).join(''):'<div class="empty">Nog geen offertes ontvangen.</div>'}catch(e){fail(e)}}
$('myQuotes').onclick=async e=>{let b=e.target.closest('[data-quote]');if(!b)return;if(!confirm('Wil je deze offerte '+(b.dataset.decision==='geaccepteerd'?'accepteren':'afwijzen')+'?'))return;try{await api('/quotes/'+b.dataset.quote,'PATCH',{status:b.dataset.decision});loadCases()}catch(err){fail(err)}};
$('cases').onclick=e=>{let b=e.target.closest('[data-match]');if(b)match(b.dataset.match,b.dataset.trade)};
$('newBtn').onclick=()=>show('landing');
function renderCategories(){$('categories').innerHTML=categories.map(c=>`<button class="category ${selected===c[0]?'selected':''}" data-cat="${c[0]}"><span>${c[1]}</span> ${c[2]}</button>`).join('')};renderCategories();
$('categories').onclick=e=>{let b=e.target.closest('[data-cat]');if(b){selected=b.dataset.cat;renderCategories()}};
$('photo').onchange=async e=>{let f=e.target.files[0];image=null;$('preview').innerHTML='';if(!f)return;if(f.size>3e6||!['image/jpeg','image/png','image/webp'].includes(f.type)){notice('Kies een JPEG-, PNG- of WebP-foto kleiner dan 3 MB.');return}image=await new Promise((resolve,reject)=>{let reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=reject;reader.readAsDataURL(f)});let img=document.createElement('img');img.src=image;img.alt='Geselecteerde schadefoto';$('preview').append(img)};
$('analyzeBtn').onclick=async()=>{if(!user){pendingGuest=true;notice('Log in of registreer om je klus te analyseren. Je ingevulde gegevens blijven bewaard.');show('auth');return}if(!selected||!$('description').value.trim()||!$('postcode').value.trim())return notice('Vul categorie, omschrijving en postcode in.');if(image&&!$('aiConsent').checked)return notice('Geef toestemming voor AI-fotoanalyse of verwijder de foto.');$('analyzeBtn').disabled=true;$('analyzeBtn').textContent='Bezig met analyseren…';try{let d=await api('/analyze','POST',{category:selected,description:$('description').value,image,aiConsent:$('aiConsent').checked});analysis=d.analysis;renderAnalysis();show('analysis')}catch(e){if(e.data?.analysis){analysis=e.data.analysis;renderAnalysis();show('analysis');notice('AI niet beschikbaar: basisinschatting getoond.')}else fail(e)}finally{$('analyzeBtn').disabled=false;$('analyzeBtn').textContent='Analyseer probleem →'}};
function renderAnalysis(){$('result').innerHTML=`<span>Urgentie: ${esc(analysis.urgency)}</span><h3>Mogelijke oorzaken</h3>${(Array.isArray(analysis.possibleCauses)?analysis.possibleCauses:[]).map(c=>`<div class="cause">${esc(c)}</div>`).join('')}<h3>Advies</h3><p>${esc(analysis.advice)}</p><h3>Passende vakman</h3><p>${esc(analysis.trade)}</p><small>${esc(analysis.disclaimer)}</small><p>${analysis.source==='gemini'?'AI-analyse uitgevoerd':'Basisregels gebruikt; geen AI-fotoanalyse uitgevoerd.'}</p>`}
$('saveBtn').onclick=async()=>{try{let d=await api('/cases','POST',{category:selected,description:$('description').value,postcode:$('postcode').value,analysis});caseId=d.id;match(caseId,analysis.trade)}catch(e){fail(e)}};
async function match(id,trade){caseId=id;show('match');$('trades').innerHTML='<div class="empty">Vakmannen laden…</div>';try{let d=await api('/trades?trade='+encodeURIComponent(trade));$('trades').innerHTML=d.trades.length?d.trades.map(t=>`<div class="case"><strong>${esc(t.name)}</strong><small>${esc(t.trade)} · ${esc(t.postcode||'Werkgebied onbekend')}</small><button class="primary" data-request="${esc(t.id)}">Verstuur aanvraag</button></div>`).join(''):'<div class="empty">Nog geen vakmannen geregistreerd voor '+esc(trade)+'. Je melding is opgeslagen.</div>'}catch(e){fail(e)}}
$('trades').onclick=async e=>{let b=e.target.closest('[data-request]');if(!b)return;b.disabled=true;try{await api('/requests','POST',{caseId,tradeId:b.dataset.request});notice('Aanvraag verzonden naar deze vakman.');show('home');loadCases()}catch(err){fail(err);b.disabled=false}};
async function loadLeads(){try{let d=await api('/requests');$('leads').innerHTML=d.requests.length?d.requests.map(r=>`<div class="case"><strong>${esc(r.category)} · ${esc(r.postcode)}</strong><small>${esc(r.created.slice(0,10))} · ${esc(r.customer)}</small><p>${esc(r.description)}</p><p>Urgentie: ${esc(r.analysis?.urgency||'Onbekend')}</p><label>Offertebedrag (€)<input type="number" min="1" step="0.01" data-amount="${esc(r.id)}" placeholder="Bijv. 125.00"></label><label>Werkzaamheden / voorwaarden<textarea data-details="${esc(r.id)}" placeholder="Wat is inbegrepen?"></textarea></label><button class="primary" data-offer="${esc(r.id)}">Offerte versturen</button><label>Status<select data-status="${esc(r.id)}"><option ${r.status==='nieuw'?'selected':''}>nieuw</option><option ${r.status==='in behandeling'?'selected':''}>in behandeling</option><option ${r.status==='afgerond'?'selected':''}>afgerond</option></select></label></div>`).join(''):'<div class="empty">Er zijn nog geen aanvragen aan jou verstuurd.</div>';let q=await api('/quotes');$('proQuotes').innerHTML=q.quotes.length?q.quotes.map(x=>`<div class="case"><b>€ ${(x.amount_cents/100).toFixed(2)}</b><p>${esc(x.details)}</p><small>Status: ${esc(x.status)}</small></div>`).join(''):'<div class="empty">Nog geen offertes uitgebracht.</div>'}catch(e){fail(e)}}
$('leads').onclick=async e=>{let b=e.target.closest('[data-offer]');if(!b)return;let id=b.dataset.offer,amount=Number(document.querySelector(`[data-amount="${id}"]`).value),details=document.querySelector(`[data-details="${id}"]`).value;if(!Number.isFinite(amount)||amount<1)return notice('Vul een geldig bedrag in.');try{await api('/quotes','POST',{requestId:id,amountCents:Math.round(amount*100),details});notice('Offerte verstuurd');loadLeads()}catch(err){fail(err)}};
$('leads').onchange=async e=>{let s=e.target.closest('[data-status]');if(s)try{await api('/requests/'+s.dataset.status,'PATCH',{status:s.value});notice('Status bijgewerkt')}catch(err){fail(err)}};
document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>{show(b.dataset.go);if(b.dataset.go==='home')loadCases()});
if(token)api('/me').then(d=>{user=d.user;start()}).catch(()=>{sessionStorage.removeItem('klusfix_token');token=null;show('landing')});
if('serviceWorker'in navigator)navigator.serviceWorker.register('/sw.js');
