'use strict';
const $=id=>document.getElementById(id);let token=sessionStorage.getItem('klusfix_token'),user=null,selected='',analysis=null,caseId=null,image=null,register=false;
const categories=[['lekkage','💧','Lekkage / waterschade'],['verwarming','🔥','Verwarming'],['elektra','⚡','Elektra'],['sanitair','🚿','Sanitair'],['dak','🏠','Dak'],['muren','🧱','Muren / plafonds'],['vloer','🪵','Vloer'],['deuren','🚪','Deuren / ramen'],['schimmel','🦠','Schimmel / vocht'],['tuin','🌳','Tuin'],['ongedierte','🐜','Ongedierte'],['apparatuur','🔌','Apparatuur']];
const trades=['Loodgieter','Elektricien','Installateur','Dakdekker','Stukadoor','Vloerspecialist','Timmerman','Vochtbestrijder','Hovenier','Ongediertebestrijder','Reparateur','Allround klusbedrijf'];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function notice(t){$('notice').textContent=t;setTimeout(()=>{if($('notice').textContent===t)$('notice').textContent=''},6000)}
function show(id){document.querySelectorAll('.screen').forEach(s=>s.classList.toggle('active',s.id===id));scrollTo(0,0)}
async function api(route,method='GET',body){let r=await fetch('/api'+route,{method,headers:{'Content-Type':'application/json',...(token?{Authorization:'Bearer '+token}:{})},body:body?JSON.stringify(body):undefined});let data=await r.json();if(!r.ok){let e=new Error(data.error||'Er ging iets mis');e.data=data;throw e}return data}
function fail(e){notice(e.message||'Er ging iets mis')}
$('trade').innerHTML=trades.map(t=>`<option>${esc(t)}</option>`).join('');
$('role').onchange=()=>{$('tradeFields').hidden=$('role').value!=='vakman'};
$('authSwitch').onclick=()=>{register=!register;document.querySelectorAll('.registerOnly').forEach(el=>el.hidden=!register);$('authTitle').textContent=register?'Account aanmaken':'Inloggen';$('authSubmit').textContent=register?'Registreren':'Inloggen';$('authSwitch').textContent=register?'Ik heb al een account':'Nog geen account? Registreren';$('tradeFields').hidden=!register||$('role').value!=='vakman';$('password').autocomplete=register?'new-password':'current-password'};
$('authForm').onsubmit=async e=>{e.preventDefault();try{let data=await api(register?'/register':'/login','POST',{email:$('email').value,password:$('password').value,name:$('name').value,role:$('role').value,trade:$('trade').value,postcode:$('workPostcode').value});token=data.token;sessionStorage.setItem('klusfix_token',token);user=data.user;start()}catch(err){fail(err)}};
$('logout').onclick=async()=>{try{await api('/logout','POST',{})}catch{}sessionStorage.removeItem('klusfix_token');token=null;user=null;$('logout').hidden=true;show('auth')};
function start(){$('logout').hidden=false;if(user.role==='vakman'){show('pro');$('proWelcome').textContent='Welkom, '+user.name;loadLeads()}else{$('welcome').textContent='Welkom, '+user.name;show('home');loadCases()}}
async function loadCases(){try{let [c,r,q]=await Promise.all([api('/cases'),api('/requests'),api('/quotes')]);$('cases').innerHTML=c.cases.length?c.cases.map(x=>`<div class="case"><strong>${esc(categories.find(a=>a[0]===x.category)?.[2]||x.category)}</strong><small>${esc(x.created.slice(0,10))} · ${esc(x.analysis.trade)}</small><p>${esc(x.description)}</p><button data-match="${esc(x.id)}" data-trade="${esc(x.analysis.trade)}">Vind vakman →</button></div>`).join(''):'<div class="empty">Nog geen meldingen.</div>';$('myRequests').innerHTML=r.requests.length?r.requests.map(x=>`<div class="case"><b>${esc(x.tradeName)}</b><p>${esc(x.description)}</p><small>Status: ${esc(x.status)}</small></div>`).join(''):'<div class="empty">Nog geen aanvragen verstuurd.</div>';$('myQuotes').innerHTML=q.quotes.length?q.quotes.map(x=>`<div class="case"><b>${esc(x.tradeName)}</b><p>€ ${(x.amount_cents/100).toFixed(2)} — ${esc(x.details)}</p><small>Status: ${esc(x.status)}</small>${x.status==='aangeboden'?`<div><button data-quote="${esc(x.id)}" data-decision="geaccepteerd">Accepteren</button><button data-quote="${esc(x.id)}" data-decision="afgewezen">Afwijzen</button></div>`:''}</div>`).join(''):'<div class="empty">Nog geen offertes ontvangen.</div>'}catch(e){fail(e)}}
$('myQuotes').onclick=async e=>{let b=e.target.closest('[data-quote]');if(!b)return;if(!confirm('Wil je deze offerte '+(b.dataset.decision==='geaccepteerd'?'accepteren':'afwijzen')+'?'))return;try{await api('/quotes/'+b.dataset.quote,'PATCH',{status:b.dataset.decision});loadCases()}catch(err){fail(err)}};
$('cases').onclick=e=>{let b=e.target.closest('[data-match]');if(b)match(b.dataset.match,b.dataset.trade)};
$('newBtn').onclick=()=>{selected='';image=null;analysis=null;$('description').value='';$('postcode').value='';$('photo').value='';$('aiConsent').checked=false;$('preview').innerHTML='';renderCategories();show('report')};
function renderCategories(){$('categories').innerHTML=categories.map(c=>`<button class="category ${selected===c[0]?'selected':''}" data-cat="${c[0]}"><span>${c[1]}</span> ${c[2]}</button>`).join('')};renderCategories();
$('categories').onclick=e=>{let b=e.target.closest('[data-cat]');if(b){selected=b.dataset.cat;renderCategories()}};
$('photo').onchange=async e=>{let f=e.target.files[0];image=null;$('preview').innerHTML='';if(!f)return;if(f.size>3e6||!['image/jpeg','image/png','image/webp'].includes(f.type)){notice('Kies een JPEG-, PNG- of WebP-foto kleiner dan 3 MB.');return}image=await new Promise((resolve,reject)=>{let reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=reject;reader.readAsDataURL(f)});let img=document.createElement('img');img.src=image;img.alt='Geselecteerde schadefoto';$('preview').append(img)};
$('analyzeBtn').onclick=async()=>{if(!selected||!$('description').value.trim()||!$('postcode').value.trim())return notice('Vul categorie, omschrijving en postcode in.');if(image&&!$('aiConsent').checked)return notice('Geef toestemming voor AI-fotoanalyse of verwijder de foto.');$('analyzeBtn').disabled=true;$('analyzeBtn').textContent='Bezig met analyseren…';try{let d=await api('/analyze','POST',{category:selected,description:$('description').value,image,aiConsent:$('aiConsent').checked});analysis=d.analysis;renderAnalysis();show('analysis')}catch(e){if(e.data?.analysis){analysis=e.data.analysis;renderAnalysis();show('analysis');notice('AI niet beschikbaar: basisinschatting getoond.')}else fail(e)}finally{$('analyzeBtn').disabled=false;$('analyzeBtn').textContent='Analyseer probleem →'}};
function renderAnalysis(){$('result').innerHTML=`<span>Urgentie: ${esc(analysis.urgency)}</span><h3>Mogelijke oorzaken</h3>${(Array.isArray(analysis.possibleCauses)?analysis.possibleCauses:[]).map(c=>`<div class="cause">${esc(c)}</div>`).join('')}<h3>Advies</h3><p>${esc(analysis.advice)}</p><h3>Passende vakman</h3><p>${esc(analysis.trade)}</p><small>${esc(analysis.disclaimer)}</small><p>${analysis.source==='gemini'?'AI-analyse uitgevoerd':'Basisregels gebruikt; geen AI-fotoanalyse uitgevoerd.'}</p>`}
$('saveBtn').onclick=async()=>{try{let d=await api('/cases','POST',{category:selected,description:$('description').value,postcode:$('postcode').value,analysis});caseId=d.id;match(caseId,analysis.trade)}catch(e){fail(e)}};
async function match(id,trade){caseId=id;show('match');$('trades').innerHTML='<div class="empty">Vakmannen laden…</div>';try{let d=await api('/trades?trade='+encodeURIComponent(trade));$('trades').innerHTML=d.trades.length?d.trades.map(t=>`<div class="case"><strong>${esc(t.name)}</strong><small>${esc(t.trade)} · ${esc(t.postcode||'Werkgebied onbekend')}</small><button class="primary" data-request="${esc(t.id)}">Verstuur aanvraag</button></div>`).join(''):'<div class="empty">Nog geen vakmannen geregistreerd voor '+esc(trade)+'. Je melding is opgeslagen.</div>'}catch(e){fail(e)}}
$('trades').onclick=async e=>{let b=e.target.closest('[data-request]');if(!b)return;b.disabled=true;try{await api('/requests','POST',{caseId,tradeId:b.dataset.request});notice('Aanvraag verzonden naar deze vakman.');show('home');loadCases()}catch(err){fail(err);b.disabled=false}};
async function loadLeads(){try{let d=await api('/requests');$('leads').innerHTML=d.requests.length?d.requests.map(r=>`<div class="case"><strong>${esc(r.category)} · ${esc(r.postcode)}</strong><small>${esc(r.created.slice(0,10))} · ${esc(r.customer)}</small><p>${esc(r.description)}</p><p>Urgentie: ${esc(r.analysis?.urgency||'Onbekend')}</p><label>Offertebedrag (€)<input type="number" min="1" step="0.01" data-amount="${esc(r.id)}" placeholder="Bijv. 125.00"></label><label>Werkzaamheden / voorwaarden<textarea data-details="${esc(r.id)}" placeholder="Wat is inbegrepen?"></textarea></label><button class="primary" data-offer="${esc(r.id)}">Offerte versturen</button><label>Status<select data-status="${esc(r.id)}"><option ${r.status==='nieuw'?'selected':''}>nieuw</option><option ${r.status==='in behandeling'?'selected':''}>in behandeling</option><option ${r.status==='afgerond'?'selected':''}>afgerond</option></select></label></div>`).join(''):'<div class="empty">Er zijn nog geen aanvragen aan jou verstuurd.</div>';let q=await api('/quotes');$('proQuotes').innerHTML=q.quotes.length?q.quotes.map(x=>`<div class="case"><b>€ ${(x.amount_cents/100).toFixed(2)}</b><p>${esc(x.details)}</p><small>Status: ${esc(x.status)}</small></div>`).join(''):'<div class="empty">Nog geen offertes uitgebracht.</div>'}catch(e){fail(e)}}
$('leads').onclick=async e=>{let b=e.target.closest('[data-offer]');if(!b)return;let id=b.dataset.offer,amount=Number(document.querySelector(`[data-amount="${id}"]`).value),details=document.querySelector(`[data-details="${id}"]`).value;if(!Number.isFinite(amount)||amount<1)return notice('Vul een geldig bedrag in.');try{await api('/quotes','POST',{requestId:id,amountCents:Math.round(amount*100),details});notice('Offerte verstuurd');loadLeads()}catch(err){fail(err)}};
$('leads').onchange=async e=>{let s=e.target.closest('[data-status]');if(s)try{await api('/requests/'+s.dataset.status,'PATCH',{status:s.value});notice('Status bijgewerkt')}catch(err){fail(err)}};
document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>{show(b.dataset.go);if(b.dataset.go==='home')loadCases()});
if(token)api('/me').then(d=>{user=d.user;start()}).catch(()=>{sessionStorage.removeItem('klusfix_token');token=null;show('auth')});
if('serviceWorker'in navigator)navigator.serviceWorker.register('/sw.js');
