'use strict';
const $=id=>document.getElementById(id);let token=sessionStorage.getItem('klusfix_token'),user=null,selected='',analysis=null,caseId=null,image=null,register=false;
const categories=[['schilder','🎨','Schilderwerkzaamheden'],['stukadoor','🧱','Stukadoor'],['lekkage','💧','Lekkage / waterschade'],['verwarming','🔥','Verwarming'],['elektra','⚡','Elektra'],['sanitair','🚿','Sanitair'],['dak','🏠','Dak'],['muren','🧱','Muren / plafonds'],['vloer','🪵','Vloer'],['deuren','🚪','Deuren / ramen'],['schimmel','🦠','Schimmel / vocht'],['tuin','🌳','Tuin'],['ongedierte','🐜','Ongedierte'],['apparatuur','🔌','Apparatuur'],['overig','💡','Overige klus']];
const landingDetails={schilder:['Schilder','Binnen- en buitenschilderwerk'],stukadoor:['Stukadoor','Muren en plafonds stucen'],lekkage:['Loodgieter','Lekkage, sanitair en water'],verwarming:['Installateur','Verwarming en cv'],elektra:['Elektricien','Elektra en stroom'],sanitair:['Sanitair','Badkamer en toilet'],dak:['Dakdekker','Dak en dakbedekking'],muren:['Muren','Metselwerk en herstel'],vloer:['Vloer','Vloeren en afwerking'],deuren:['Deuren','Deuren en kozijnen'],schimmel:['Schimmel','Vochtbestrijding'],tuin:['Tuin','Tuinaanleg en onderhoud'],ongedierte:['Ongedierte','Ongediertebestrijding'],apparatuur:['Apparatuur','Reparatie en installatie'],overig:['Overige klus','Vertel ons wat je nodig hebt']};
// Vaste SVG-lijniconen: geen emoji of externe iconenbibliotheek nodig.
const iconPaths={
schilder:'<path d="M4 5h12a2 2 0 0 1 2 2v3a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V7a2 2 0 0 1 2-2Z" fill="#ffcf27" stroke="#fff"/><path d="M4 5h12" stroke="#fff6c8" stroke-width="1.5"/><path d="M18 8h2a2 2 0 0 1 2 2v4a2 2 0 0 1-2 2h-9v2" stroke="#f9ffff" stroke-width="1.8"/><path d="M13 12v3m3-3v2" stroke="#ffcf27" stroke-width="2.2"/><path d="M9 18h4v5a2 2 0 0 1-4 0Z" fill="#20c98a" stroke="#fff"/>',
stukadoor:'<path d="M3 12 17 3l4 6L7 18Z" fill="#b5c8d8" stroke="#fff" stroke-width="1.5"/><path d="m5 12 12-8" stroke="#f6ffff" stroke-width="1.4"/><path d="m8 17-4 5" stroke="#f9ffff" stroke-width="2"/><path d="m3 22 5-6" stroke="#29d996" stroke-width="4"/>',
lekkage:'<path d="M12 2C9 7 4 12 4 16a8 8 0 0 0 16 0c0-4-5-9-8-14Z" fill="#168ee5" stroke="#b4eaff" stroke-width="1.4"/><path d="M8 16c0 2 1 3 3 4" stroke="#d9f8ff" stroke-width="1.6"/>',
verwarming:'<path d="M10 14V5a2 2 0 0 1 4 0v9a5 5 0 1 1-4 0Z" fill="#164b43" stroke="#fff" stroke-width="1.6"/><path d="M12 8v10" stroke="#ff7650" stroke-width="2.4"/><circle cx="12" cy="19" r="2.4" fill="#ff6948" stroke="none"/>',
elektra:'<path d="m13 2-9 12h7l-1 8 10-13h-7Z" fill="#ffd044" stroke="#fff1b0" stroke-width="1.4"/>',
sanitair:'<path d="M3 12h18v2a8 8 0 0 1-8 8h-2a8 8 0 0 1-8-8Z" fill="#1889d6" stroke="#fff" stroke-width="1.4"/><path d="M7 12V6a3 3 0 0 1 6 0m-2 0h5M8 22v-2m8 2v-2" stroke="#f5ffff" stroke-width="1.6"/>',
dak:'<path d="m2 11 10-8 10 8" stroke="#ff7745" stroke-width="2.7"/><path d="M5 10v11h14V10M9 21v-7h6v7" stroke="#fff" stroke-width="1.5"/>',
muren:'<rect x="2" y="4" width="20" height="16" rx="1" fill="#e86b4d" stroke="#fff"/><path d="M2 9h20M2 14h20M2 19h20M9 4v5m7 0v5m-7 0v5" stroke="#fff" stroke-width="1.4"/>',
vloer:'<path d="M6 4h16l-5 16H2Z" fill="#839bc0" stroke="#fff" stroke-width="1.4"/><path d="M12 4 7 20M4 12h15" stroke="#fff" stroke-width="1.3"/>',
deuren:'<path d="M5 2h14v20H5Z" stroke="#fff" stroke-width="1.5"/><path d="m8 5 8-1v16l-8-1Z" fill="#8c644a" stroke="#fff" stroke-width="1.3"/><circle cx="13" cy="12" r=".9" fill="#ffd34d" stroke="none"/>',
schimmel:'<circle cx="12" cy="12" r="6.5" fill="#9263ca" stroke="#d9b9ff" stroke-width="1.5"/><path d="M12 1v4m0 14v4M1 12h4m14 0h4M4 4l3 3m10 10 3 3M20 4l-3 3M7 17l-3 3" stroke="#c8a0f6" stroke-width="2"/><circle cx="10" cy="10" r="1.3" fill="#e6d2ff" stroke="none"/>',
tuin:'<path d="M12 22V11M12 15C4 15 3 9 4 5c6 0 8 4 8 10Zm0-3c0-6 3-9 8-9 1 6-2 9-8 9Z" fill="#2bbd76" stroke="#a9f6c5" stroke-width="1.4"/><path d="M7 22h10" stroke="#fff" stroke-width="1.5"/>',
ongedierte:'<path d="M8 8a4 4 0 0 1 8 0M7 12a5 5 0 0 1 10 0v5a5 5 0 0 1-10 0Z" fill="#e66d50" stroke="#ffb196" stroke-width="1.5"/><path d="M12 12v10M4 10l3 2m13-2-3 2M3 16h4m14 0h-4M5 21l3-3m11 3-3-3" stroke="#ffb196" stroke-width="1.5"/>',
apparatuur:'<rect x="4" y="2" width="16" height="20" rx="2" fill="#fff" stroke="#fff"/><circle cx="12" cy="14" r="5" fill="#167ab1" stroke="#85dcff" stroke-width="1.3"/><path d="M7 6h2m3 0h5" stroke="#218ad1" stroke-width="1.4"/>',
overig:'<path d="M9 18h6m-5 3h4M9 15c-5-4-3-11 3-11s8 7 3 11l-1 3h-4Z" stroke="#44e5a5" stroke-width="1.5"/>'
};
function tradeIcon(id){return `<svg class="trade-svg trade-svg-${id}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.35" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${iconPaths[id]||iconPaths.overig}</svg>`}

let pendingGuest=false;
function renderLanding(){$('landingCategories').innerHTML=categories.filter(([id])=>id!=='overig').map(([id])=>{let [name,desc]=landingDetails[id];return `<button type="button" class="landing-card ${id==='schilder'||id==='stukadoor'?'featured':''}" data-landing="${id}"><span class="landing-icon">${tradeIcon(id)}</span><span class="landing-copy"><strong>${esc(name)}</strong><small>${esc(desc)}</small></span><span class="landing-arrow" aria-hidden="true">›</span></button>`}).join('')}
function openWork(id){selected=id;image=null;analysis=null;$('description').value='';$('postcode').value=user?.postcode||'';$('photo').value='';$('aiConsent').checked=false;$('preview').innerHTML='';renderCategories();show('report')}
$('landingCategories').onclick=e=>{let b=e.target.closest('[data-landing]');if(b)openWork(b.dataset.landing)};
$('otherWork').onclick=()=>openWork('overig');
$('brand').onclick=()=>show('landing');
$('accountBtn').onclick=()=>{if(user)show(user.role==='vakman'?'pro':'home');else show('auth')};
const trades=['Schilder','Stukadoor','Loodgieter','Elektricien','Installateur','Dakdekker','Vloerspecialist','Timmerman','Vochtbestrijder','Hovenier','Ongediertebestrijder','Reparateur','Allround klusbedrijf'];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
renderLanding();
function notice(t){$('notice').textContent=t;setTimeout(()=>{if($('notice').textContent===t)$('notice').textContent=''},6000)}
function show(id){document.querySelectorAll('.screen').forEach(s=>s.classList.toggle('active',s.id===id));scrollTo(0,0)}
async function api(route,method='GET',body){let r=await fetch('/api'+route,{method,headers:{'Content-Type':'application/json',...(token?{Authorization:'Bearer '+token}:{})},body:body?JSON.stringify(body):undefined});let data=await r.json();if(!r.ok){let e=new Error(data.error||'Er ging iets mis');e.data=data;throw e}return data}
function fail(e){notice(e.message||'Er ging iets mis')}
$('trade').innerHTML=trades.map(t=>`<option>${esc(t)}</option>`).join('');
$('role').onchange=()=>{$('tradeFields').hidden=$('role').value!=='vakman'};
$('proSignupBtn').onclick=()=>{pendingGuest=false;if(!register)$('authSwitch').click();$('role').value='vakman';$('tradeFields').hidden=false;show('auth');};
$('authSwitch').onclick=()=>{register=!register;document.querySelectorAll('.registerOnly').forEach(el=>el.hidden=!register);$('authTitle').textContent=register?'Account aanmaken':'Inloggen';$('authSubmit').textContent=register?'Registreren':'Inloggen';$('authSwitch').textContent=register?'Ik heb al een account':'Nog geen account? Registreren';$('tradeFields').hidden=!register||$('role').value!=='vakman';$('password').autocomplete=register?'new-password':'current-password'};
$('authForm').onsubmit=async e=>{e.preventDefault();try{let data=await api(register?'/register':'/login','POST',{email:$('email').value,password:$('password').value,name:$('name').value,role:$('role').value,trade:$('trade').value,postcode:$('workPostcode').value});token=data.token;sessionStorage.setItem('klusfix_token',token);user=data.user;if(pendingGuest){pendingGuest=false;$('logout').hidden=false;$('accountBtn').textContent='Mijn overzicht';show('report')}else start()}catch(err){fail(err)}};
$('logout').onclick=async()=>{try{await api('/logout','POST',{})}catch{}sessionStorage.removeItem('klusfix_token');token=null;user=null;$('logout').hidden=true;$('accountBtn').textContent='Inloggen';show('landing')};
function start(){$('logout').hidden=false;$('accountBtn').textContent='Mijn overzicht';if(user.role==='vakman'){show('pro');$('proWelcome').textContent='Welkom, '+user.name;loadLeads()}else{$('welcome').textContent='Welkom, '+user.name;show('landing');loadCases()}}
async function loadCases(){try{let [c,r,q]=await Promise.all([api('/cases'),api('/requests'),api('/quotes')]);$('cases').innerHTML=c.cases.length?c.cases.map(x=>`<div class="case"><strong>${esc(categories.find(a=>a[0]===x.category)?.[2]||x.category)}</strong><small>${esc(x.created.slice(0,10))} · ${esc(x.analysis.trade)}</small><p>${esc(x.description)}</p><button data-match="${esc(x.id)}" data-trade="${esc(x.analysis.trade)}">Vind vakman →</button></div>`).join(''):'<div class="empty">Nog geen meldingen.</div>';$('myRequests').innerHTML=r.requests.length?r.requests.map(x=>`<div class="case"><b>${esc(x.tradeName)}</b><p>${esc(x.description)}</p><small>Status: ${esc(x.status)}</small></div>`).join(''):'<div class="empty">Nog geen aanvragen verstuurd.</div>';$('myQuotes').innerHTML=q.quotes.length?q.quotes.map(x=>`<div class="case"><b>${esc(x.tradeName)}</b><p>€ ${(x.amount_cents/100).toFixed(2)} — ${esc(x.details)}</p><small>Status: ${esc(x.status)}</small>${x.status==='aangeboden'?`<div><button data-quote="${esc(x.id)}" data-decision="geaccepteerd">Accepteren</button><button data-quote="${esc(x.id)}" data-decision="afgewezen">Afwijzen</button></div>`:''}</div>`).join(''):'<div class="empty">Nog geen offertes ontvangen.</div>'}catch(e){fail(e)}}
$('myQuotes').onclick=async e=>{let b=e.target.closest('[data-quote]');if(!b)return;if(!confirm('Wil je deze offerte '+(b.dataset.decision==='geaccepteerd'?'accepteren':'afwijzen')+'?'))return;try{await api('/quotes/'+b.dataset.quote,'PATCH',{status:b.dataset.decision});loadCases()}catch(err){fail(err)}};
$('cases').onclick=e=>{let b=e.target.closest('[data-match]');if(b)match(b.dataset.match,b.dataset.trade)};
$('newBtn').onclick=()=>show('landing');
function renderCategories(){$('categories').innerHTML=categories.map(c=>`<button class="category ${selected===c[0]?'selected':''}" data-cat="${c[0]}"><span>${c[1]}</span> ${c[2]}</button>`).join('')};renderCategories();
$('categories').onclick=e=>{let b=e.target.closest('[data-cat]');if(b){selected=b.dataset.cat;renderCategories()}};
$('photo').onchange=async e=>{let f=e.target.files[0];image=null;$('preview').innerHTML='';if(!f)return;if(f.size>3e6||!['image/jpeg','image/png','image/webp'].includes(f.type)){notice('Kies een JPEG-, PNG- of WebP-foto kleiner dan 3 MB.');return}image=await new Promise((resolve,reject)=>{let reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=reject;reader.readAsDataURL(f)});let img=document.createElement('img');img.src=image;img.alt='Geselecteerde schadefoto';$('preview').append(img)};
$('analyzeBtn').onclick=async()=>{if(!user){pendingGuest=true;notice('Log in of registreer om je klus te analyseren. Je ingevulde gegevens blijven bewaard.');show('auth');return}if(!selected||!$('description').value.trim()||!$('postcode').value.trim())return notice('Vul categorie, omschrijving en postcode in.');if(image&&!$('aiConsent').checked)return notice('Geef toestemming voor AI-fotoanalyse of verwijder de foto.');$('analyzeBtn').disabled=true;$('analyzeBtn').textContent='Bezig met analyseren…';try{let d=await api('/analyze','POST',{category:selected,description:$('description').value,image,aiConsent:$('aiConsent').checked});analysis=d.analysis;renderAnalysis();show('analysis')}catch(e){if(e.data?.analysis){analysis=e.data.analysis;renderAnalysis();show('analysis');notice('AI niet beschikbaar: basisinschatting getoond.')}else fail(e)}finally{$('analyzeBtn').disabled=false;$('analyzeBtn').textContent='Analyseer probleem →'}};
function renderAnalysis(){$('result').innerHTML=`<span>Urgentie: ${esc(analysis.urgency)}</span><h3>Mogelijke oorzaken</h3>${(Array.isArray(analysis.possibleCauses)?analysis.possibleCauses:[]).map(c=>`<div class="cause">${esc(c)}</div>`).join('')}<h3>Advies</h3><p>${esc(analysis.advice)}</p><h3>Passende vakman</h3><p>${esc(analysis.trade)}</p><small>${esc(analysis.disclaimer)}</small><p>${analysis.source==='gemini'?'AI-analyse uitgevoerd':'Basisregels gebruikt; geen AI-fotoanalyse uitgevoerd.'}</p>`}
$('saveBtn').onclick=async()=>{try{let d=await api('/cases','POST',{category:selected,description:$('description').value,postcode:$('postcode').value,analysis});caseId=d.id;match(caseId,analysis.trade)}catch(e){fail(e)}};
async function match(id,trade){caseId=id;show('match');$('trades').innerHTML='<div class="empty">Vakmannen laden…</div>';try{let d=await api('/trades?trade='+encodeURIComponent(trade));$('trades').innerHTML=d.trades.length?d.trades.map(t=>`<div class="case"><strong>${esc(t.name)}</strong><small>${esc(t.trade)} · ${esc(t.postcode||'Werkgebied onbekend')}</small><button class="primary" data-request="${esc(t.id)}">Verstuur aanvraag</button></div>`).join(''):'<div class="empty">Nog geen vakmannen geregistreerd voor '+esc(trade)+'. Je melding is opgeslagen.</div>'}catch(e){fail(e)}}
$('trades').onclick=async e=>{let b=e.target.closest('[data-request]');if(!b)return;b.disabled=true;try{await api('/requests','POST',{caseId,tradeId:b.dataset.request});notice('Aanvraag verzonden naar deze vakman.');show('home');loadCases()}catch(err){fail(err);b.disabled=false}};
async function loadLeads(){try{let d=await api('/requests');$('leads').innerHTML=d.requests.length?d.requests.map(r=>`<div class="case"><strong>${esc(r.category)} · ${esc(r.postcode)}</strong><small>${esc(r.created.slice(0,10))} · ${esc(r.customer)}</small><p>${esc(r.description)}</p><p>Urgentie: ${esc(r.analysis?.urgency||'Onbekend')}</p><label>Offertebedrag (€)<input type="number" min="1" step="0.01" data-amount="${esc(r.id)}" placeholder="Bijv. 125.00"></label><label>Werkzaamheden / voorwaarden<textarea data-details="${esc(r.id)}" placeholder="Wat is inbegrepen?"></textarea></label><button class="primary" data-offer="${esc(r.id)}">Offerte versturen</button><label>Status<select data-status="${esc(r.id)}"><option ${r.status==='nieuw'?'selected':''}>nieuw</option><option ${r.status==='in behandeling'?'selected':''}>in behandeling</option><option ${r.status==='afgerond'?'selected':''}>afgerond</option></select></label></div>`).join(''):'<div class="empty">Er zijn nog geen aanvragen aan jou verstuurd.</div>';let q=await api('/quotes');$('proQuotes').innerHTML=q.quotes.length?q.quotes.map(x=>`<div class="case"><b>€ ${(x.amount_cents/100).toFixed(2)}</b><p>${esc(x.details)}</p><small>Status: ${esc(x.status)}</small></div>`).join(''):'<div class="empty">Nog geen offertes uitgebracht.</div>'}catch(e){fail(e)}}
$('leads').onclick=async e=>{let b=e.target.closest('[data-offer]');if(!b)return;let id=b.dataset.offer,amount=Number(document.querySelector(`[data-amount="${id}"]`).value),details=document.querySelector(`[data-details="${id}"]`).value;if(!Number.isFinite(amount)||amount<1)return notice('Vul een geldig bedrag in.');try{await api('/quotes','POST',{requestId:id,amountCents:Math.round(amount*100),details});notice('Offerte verstuurd');loadLeads()}catch(err){fail(err)}};
$('leads').onchange=async e=>{let s=e.target.closest('[data-status]');if(s)try{await api('/requests/'+s.dataset.status,'PATCH',{status:s.value});notice('Status bijgewerkt')}catch(err){fail(err)}};
document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>{show(b.dataset.go);if(b.dataset.go==='home')loadCases()});
if(token)api('/me').then(d=>{user=d.user;start()}).catch(()=>{sessionStorage.removeItem('klusfix_token');token=null;show('landing')});
if('serviceWorker'in navigator)navigator.serviceWorker.register('/sw.js');
