'use strict';
const http=require('node:http'),fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const {DatabaseSync}=require('node:sqlite');
const dbPath=process.env.DB_PATH||path.join(__dirname,'klusfix.sqlite');
fs.mkdirSync(path.dirname(dbPath),{recursive:true});
const db=new DatabaseSync(dbPath);
db.exec(`CREATE TABLE IF NOT EXISTS users(id TEXT PRIMARY KEY,email TEXT UNIQUE NOT NULL,hash TEXT NOT NULL,role TEXT NOT NULL,name TEXT NOT NULL,trade TEXT NOT NULL DEFAULT '',postcode TEXT NOT NULL DEFAULT '');CREATE TABLE IF NOT EXISTS sessions(token TEXT PRIMARY KEY,user_id TEXT NOT NULL,expires INTEGER NOT NULL);CREATE TABLE IF NOT EXISTS cases(id TEXT PRIMARY KEY,owner_id TEXT NOT NULL,category TEXT NOT NULL,description TEXT NOT NULL,postcode TEXT NOT NULL,analysis TEXT NOT NULL,status TEXT NOT NULL,created TEXT NOT NULL);CREATE TABLE IF NOT EXISTS requests(id TEXT PRIMARY KEY,case_id TEXT NOT NULL,trade_id TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'nieuw',created TEXT NOT NULL);`);
db.exec(`CREATE TABLE IF NOT EXISTS quotes(id TEXT PRIMARY KEY,request_id TEXT NOT NULL UNIQUE,trade_id TEXT NOT NULL,amount_cents INTEGER NOT NULL,details TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'aangeboden',created TEXT NOT NULL);`);
const root=__dirname, port=Number(process.env.PORT||8080), key=process.env.GEMINI_API_KEY||'';
const mime={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css','.webmanifest':'application/manifest+json','.svg':'image/svg+xml'};
function send(res,status,data){res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store','X-Content-Type-Options':'nosniff'});res.end(JSON.stringify(data))}
function read(req){return new Promise((resolve,reject)=>{let b='',n=0;req.on('data',c=>{n+=c.length;if(n>7e6){reject(Error('Aanvraag te groot'));req.destroy()}else b+=c});req.on('end',()=>{try{resolve(JSON.parse(b||'{}'))}catch{reject(Error('Ongeldige JSON'))}});req.on('error',reject)})}
const uid=()=>crypto.randomUUID();
function auth(req){let token=(req.headers.authorization||'').replace(/^Bearer /,'');return db.prepare('SELECT users.* FROM users JOIN sessions ON users.id=sessions.user_id WHERE sessions.token=? AND sessions.expires>?').get(token,Date.now())}
function safeUser(u){return {id:u.id,email:u.email,role:u.role,name:u.name,trade:u.trade,postcode:u.postcode}}
const trades={lekkage:'Loodgieter',elektra:'Elektricien',verwarming:'Installateur',sanitair:'Loodgieter',dak:'Dakdekker',muren:'Stukadoor',vloer:'Vloerspecialist',deuren:'Timmerman',schimmel:'Vochtbestrijder',tuin:'Hovenier',ongedierte:'Ongediertebestrijder',apparatuur:'Reparateur'};
function fallback(category,description){return {source:'basisregels',urgency:/gaslucht|rook|vonken|brand|stroom op water/i.test(description)?'Spoed':'Onbekend',possibleCauses:['Oorzaak niet vastgesteld; inspectie ter plaatse nodig'],advice:'Laat het probleem door een geschikte vakman beoordelen. Bij direct gevaar: verlaat de gevaarlijke situatie en bel indien nodig 112.',trade:trades[category]||'Allround klusbedrijf',disclaimer:'Geen diagnose. De foto is niet door AI beoordeeld.'}}
async function analyze(body){let base=fallback(body.category,body.description);if(!key)return base;
let parts=[{text:`Je bent een voorzichtige Nederlandstalige triage-assistent voor woningproblemen. Geef uitsluitend geldig JSON met keys urgency (Spoed, Hoog, Normaal of Onbekend), possibleCauses (max 3 korte mogelijke oorzaken), advice (max 100 woorden), trade (vakman). Beschrijf onzekerheid; geen definitieve diagnose of aansprakelijkheid. Bij mogelijk gas, elektriciteit, brand of constructiegevaar adviseer direct veilig handelen en professionele hulp. Categorie: ${String(body.category).slice(0,50)}. Omschrijving: ${String(body.description).slice(0,2000)}. Vragen: ${JSON.stringify(body.answers||{}).slice(0,1000)}`}];
if(body.image&&/^data:image\/(jpeg|png|webp);base64,/.test(body.image)){let [head,data]=body.image.split(',');if(data.length<5e6)parts.push({inline_data:{mime_type:head.slice(5,-7),data}})}
const response=await fetch('https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent',{method:'POST',headers:{'Content-Type':'application/json','x-goog-api-key':key},body:JSON.stringify({contents:[{parts}],generationConfig:{responseMimeType:'application/json',temperature:0.2}}),signal:AbortSignal.timeout(25000)});
if(!response.ok)throw Error('AI-dienst tijdelijk niet beschikbaar ('+response.status+')');let json=await response.json();let result=JSON.parse(json.candidates?.[0]?.content?.parts?.map(p=>p.text||'').join('')||'{}');return {...base,...result,source:'gemini',disclaimer:'AI-inschatting, geen definitieve diagnose. Laat de oorzaak ter plaatse controleren.'};}
async function api(req,res,url){const route=url.pathname,method=req.method;let body={};if(['POST','PATCH'].includes(method))body=await read(req);
if(route==='/api/status')return send(res,200,{aiConfigured:!!key,database:'SQLite',mode:'private-test'});
if(route==='/api/register'&&method==='POST'){let {email,password,name,role,trade,postcode}=body;email=String(email||'').trim().toLowerCase();if(!/^\S+@\S+\.\S+$/.test(email)||String(password||'').length<10||!['consument','vakman'].includes(role)||!String(name||'').trim())return send(res,400,{error:'Vul naam, geldig e-mailadres en wachtwoord van minimaal 10 tekens in.'});if(role==='vakman'&&!trade)return send(res,400,{error:'Kies je vakgebied.'});let salt=crypto.randomBytes(16).toString('hex'),hash=salt+':'+crypto.scryptSync(password,salt,64).toString('hex'),id=uid();try{db.prepare('INSERT INTO users(id,email,hash,role,name,trade,postcode) VALUES(?,?,?,?,?,?,?)').run(id,email,hash,role,name,role==='vakman'?String(trade):'',String(postcode||''));}catch{return send(res,409,{error:'Dit e-mailadres is al geregistreerd.'})}return loginUser(res,db.prepare('SELECT * FROM users WHERE id=?').get(id))}
if(route==='/api/login'&&method==='POST'){let u=db.prepare('SELECT * FROM users WHERE email=?').get(String(body.email||'').trim().toLowerCase());if(!u)return send(res,401,{error:'Ongeldige inloggegevens'});let [salt,stored]=u.hash.split(':'),actual=crypto.scryptSync(String(body.password||''),salt,64);if(!crypto.timingSafeEqual(actual,Buffer.from(stored,'hex')))return send(res,401,{error:'Ongeldige inloggegevens'});return loginUser(res,u)}
let user=auth(req);if(!user)return send(res,401,{error:'Log eerst in.'});
if(route==='/api/logout'&&method==='POST'){db.prepare('DELETE FROM sessions WHERE token=?').run((req.headers.authorization||'').replace(/^Bearer /,''));return send(res,200,{ok:true})}
if(route==='/api/me')return send(res,200,{user:safeUser(user)});
if(route==='/api/analyze'&&method==='POST'){if(user.role!=='consument')return send(res,403,{error:'Alleen voor consumenten'});if(!trades[body.category]||!String(body.description||'').trim())return send(res,400,{error:'Selecteer een categorie en vul een omschrijving in.'});if(body.image&&!body.aiConsent)return send(res,400,{error:'Geef toestemming voor fotoanalyse of verwijder de foto.'});try{return send(res,200,{analysis:await analyze(body)})}catch(e){return send(res,503,{error:e.message,analysis:fallback(body.category,body.description)})}}
if(route==='/api/cases'&&method==='POST'){if(user.role!=='consument')return send(res,403,{error:'Alleen voor consumenten'});if(!trades[body.category]||!String(body.description||'').trim()||!String(body.postcode||'').trim())return send(res,400,{error:'Categorie, omschrijving en postcode verplicht'});let id=uid(),analysis=fallback(body.category,body.description);if(body.analysis&&typeof body.analysis==='object'){analysis={source:['gemini','basisregels'].includes(body.analysis.source)?body.analysis.source:'basisregels',urgency:String(body.analysis.urgency||'Onbekend').slice(0,40),possibleCauses:Array.isArray(body.analysis.possibleCauses)?body.analysis.possibleCauses.slice(0,3).map(x=>String(x).slice(0,200)):analysis.possibleCauses,advice:String(body.analysis.advice||'').slice(0,1000),trade:trades[body.category],disclaimer:'Indicatie, geen diagnose.'}}db.prepare('INSERT INTO cases VALUES(?,?,?,?,?,?,?,?)').run(id,user.id,body.category,String(body.description).slice(0,3000),String(body.postcode).slice(0,20),JSON.stringify(analysis),'open',new Date().toISOString());return send(res,201,{id})}
if(route==='/api/cases'&&method==='GET'){let rows=db.prepare('SELECT * FROM cases WHERE owner_id=? ORDER BY created DESC').all(user.id);return send(res,200,{cases:rows.map(r=>({...r,analysis:JSON.parse(r.analysis)}))})}
if(route==='/api/trades'&&method==='GET'){let rows=db.prepare('SELECT id,name,trade,postcode FROM users WHERE role=? AND trade=?').all('vakman',String(url.searchParams.get('trade')||''));return send(res,200,{trades:rows})}
if(route==='/api/requests'&&method==='POST'){let c=db.prepare('SELECT * FROM cases WHERE id=? AND owner_id=?').get(body.caseId,user.id),t=db.prepare('SELECT * FROM users WHERE id=? AND role=?').get(body.tradeId,'vakman');if(!c||!t||JSON.parse(c.analysis).trade!==t.trade)return send(res,400,{error:'Ongeldige aanvraag of vakman'});let exists=db.prepare('SELECT id FROM requests WHERE case_id=? AND trade_id=?').get(c.id,t.id);if(exists)return send(res,409,{error:'Deze aanvraag is al verstuurd'});let id=uid();db.prepare('INSERT INTO requests(id,case_id,trade_id,created) VALUES(?,?,?,?)').run(id,c.id,t.id,new Date().toISOString());return send(res,201,{id})}
if(route==='/api/requests'&&method==='GET'){let rows=user.role==='vakman'?db.prepare('SELECT requests.*,cases.category,cases.description,cases.postcode,cases.analysis,users.name AS customer FROM requests JOIN cases ON cases.id=requests.case_id JOIN users ON users.id=cases.owner_id WHERE requests.trade_id=? ORDER BY requests.created DESC').all(user.id):db.prepare('SELECT requests.*,users.name AS tradeName,users.trade,cases.description FROM requests JOIN users ON users.id=requests.trade_id JOIN cases ON cases.id=requests.case_id WHERE cases.owner_id=? ORDER BY requests.created DESC').all(user.id);return send(res,200,{requests:rows.map(r=>({...r,analysis:r.analysis?JSON.parse(r.analysis):undefined}))})}
if(route==='/api/quotes'&&method==='POST'){
if(user.role!=='vakman')return send(res,403,{error:'Alleen voor vakmannen'});
let r=db.prepare('SELECT * FROM requests WHERE id=? AND trade_id=?').get(body.requestId,user.id);
let amount=Number(body.amountCents),details=String(body.details||'').trim();
if(!r)return send(res,404,{error:'Aanvraag niet gevonden'});
if(!Number.isSafeInteger(amount)||amount<100||amount>100000000||details.length<10||details.length>2000)return send(res,400,{error:'Vul een geldig bedrag en een omschrijving van 10 tot 2000 tekens in.'});
let existing=db.prepare('SELECT id FROM quotes WHERE request_id=?').get(r.id);
if(existing)return send(res,409,{error:'Voor deze aanvraag is al een offerte ingediend.'});
let id=uid();db.prepare('INSERT INTO quotes(id,request_id,trade_id,amount_cents,details,created) VALUES(?,?,?,?,?,?)').run(id,r.id,user.id,amount,details,new Date().toISOString());
return send(res,201,{id});}
if(route==='/api/quotes'&&method==='GET'){
let rows=user.role==='vakman'?db.prepare('SELECT quotes.* FROM quotes WHERE trade_id=? ORDER BY created DESC').all(user.id):db.prepare('SELECT quotes.*,users.name AS tradeName FROM quotes JOIN requests ON requests.id=quotes.request_id JOIN cases ON cases.id=requests.case_id JOIN users ON users.id=quotes.trade_id WHERE cases.owner_id=? ORDER BY quotes.created DESC').all(user.id);
return send(res,200,{quotes:rows});}
if(route.startsWith('/api/quotes/')&&method==='PATCH'){
if(user.role!=='consument'||!['geaccepteerd','afgewezen'].includes(body.status))return send(res,403,{error:'Niet toegestaan'});
let id=route.split('/')[3];let q=db.prepare('SELECT quotes.* FROM quotes JOIN requests ON requests.id=quotes.request_id JOIN cases ON cases.id=requests.case_id WHERE quotes.id=? AND cases.owner_id=?').get(id,user.id);
if(!q)return send(res,404,{error:'Offerte niet gevonden'});if(q.status!=='aangeboden')return send(res,409,{error:'Offerte is al beoordeeld'});
db.prepare('UPDATE quotes SET status=? WHERE id=?').run(body.status,id);return send(res,200,{ok:true});}
if(route.startsWith('/api/requests/')&&method==='PATCH'&&user.role==='vakman'){let id=route.split('/')[3];if(!['nieuw','in behandeling','afgerond'].includes(body.status))return send(res,400,{error:'Ongeldige status'});let r=db.prepare('UPDATE requests SET status=? WHERE id=? AND trade_id=?').run(body.status,id,user.id);return send(res,r.changes?200:404,r.changes?{ok:true}:{error:'Niet gevonden'})}
return send(res,404,{error:'Niet gevonden'});
}
function loginUser(res,u){let token=crypto.randomBytes(32).toString('hex');db.prepare('INSERT INTO sessions VALUES(?,?,?)').run(token,u.id,Date.now()+7*864e5);return send(res,200,{token,user:safeUser(u)})}
const server=http.createServer(async(req,res)=>{try{let url=new URL(req.url,'http://localhost');if(url.pathname.startsWith('/api/'))return await api(req,res,url);let p=url.pathname==='/'?'/index.html':url.pathname;if(!['/index.html','/app.js','/style.css','/manifest.webmanifest','/sw.js','/icon.svg'].includes(p))return send(res,404,{error:'Niet gevonden'});let file=path.join(root,p);fs.readFile(file,(err,data)=>{if(err)return send(res,404,{error:'Niet gevonden'});res.writeHead(200,{'Content-Type':mime[path.extname(file)]||'application/octet-stream','X-Content-Type-Options':'nosniff','X-Frame-Options':'DENY','Referrer-Policy':'no-referrer','Content-Security-Policy':"default-src 'self'; img-src 'self' data: blob:; style-src 'self'; script-src 'self'; connect-src 'self'; object-src 'none'; base-uri 'none'; frame-ancestors 'none'"});res.end(data)})}catch(e){(console.error('Serverfout:',e),send(res,500,{error:'Er is iets misgegaan.'}))}});
server.listen(port,()=>console.log(`KlusFix v3: http://localhost:${port} | AI ${key?'actief':'niet ingesteld'}`));
